baseURL: "https://sinkov.github.io"
languageCode: en-us
title: My New Hugo Site
theme: "ananke"

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableEmoji: true
enableRobotsTXT: true
canonifyURLs: true
publishDir: "public"
markup.goldmark.renderer: 
  unsafe: true
blackfriday:
  hrefTargetBlank: true
languages:
  en:
    title: Evgenii Sinkov
    weight: 1
    contentDir: content/en
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  text_color: ''
  author: ''
  favicon: ''
  site_logo: ''
  description: The last theme you'll ever need. Maybe.
  background_color_class: bg-black
  recent_posts_number: 3
  ananke_socials:
    - name: linkedin
      url: 'https://www.linkedin.com/in/sinkovevgeny/'
    - name: github
      url: 'https://github.com/sinkov'
    - name: CV
      url: 'https://drive.google.com/file/d/1Ymz2YXoE-pb-nCGYsrNDUT0Ed2pdCeXS/view?usp=sharing'
    - name: Superprof
      url: 'https://www.superprof.co.uk/pro-tennis-player-attentive-and-passionate-guarantee-your-joy-and-progress-any-level.html'

